### ISSUE TITLE
'unescape' is deprecated

### ISSUE THREAD

**Issue by cristi-badila** [satazor/SparkMD5#28]
I noticed that in the ``toUtf8`` function you are using the ``unescape`` method which was [deprecated](https://developer.mozilla.org/ro/docs/Web/JavaScript/Reference/Global_Objects/unescape). Wouldn't using ``decodeURIComponent`` achieve the same goal?

**Comment by satazor** [comment]
`decodeURIComponent` is already there, but both need to be used, see: http://ecmanaut.blogspot.pt/2006/07/encoding-decoding-utf8-in-javascript.html

Browser's can't simply remove methods from their engine otherwise they would break a lot of sites, see this comment: http://ecmanaut.blogspot.pt/2006/07/encoding-decoding-utf8-in-javascript.html#comment-785303118

If they ever remove it, I will either polyfill the method or do it in plain JavaScript.
